version: '3.9'
services:
  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
  api:
    build: ./backend
    image: python:alpine3.20
    depends_on:
    - "mongodb"
    ports:
    - 8080:8080
  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
    - 80:3000
    depends_on:
    - "api"